# Generated by Django 4.2.6 on 2023-10-22 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0006_alter_bed_bed_number_alter_room_room_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('bed_number', 'room')},
        ),
    ]
